### ISSUE TITLE
Setting channel_id as channel.

### ISSUE THREAD

**Issue by errodr** [mcrumm/phlack#24]
We are trying to use an incoming webhook to post data into a private group. Per Slack support, in order to do this we must use the private group's channel id instead of the channel name.

This is not possible with the way that Phlack currently handles the setting of a channel for a message. Phlack will prepend a '**#**' character to a channel if one does not exist. This causes an issue because a channel_id does not contain a '**#**' character at the beginning. An example of a channel_id is: **G0XYDSE5R**.

I would be glad create a pull request to add this functionality but I wanted to get your feedback on a proposed solution first. What I propose is that if passed a channel with a leading '**:**' character it would strip off the '**:**' and leave a clean channel id.

In Message.php I would change the channel normalizer from:

```php
function (Options $options, $value) {
    return empty($value) ? $value : (0 === strpos($value, '#') ? $value : (0 === strpos($value, '@') ? $value : '#' . $value));
}
```

to

```php
function (Options $options, $value) {
    return empty($value) ? $value : (0 === strpos($value, ':') ? ltrim($value, ':') : (0 === strpos($value, '#') ? $value : (0 === strpos($value, '@') ? $value : '#' . $value)));
}
```

also in Message.php I would change setChannel from:

```php
public function setChannel($channel)
{
    if (!empty($channel)) {
        $this->data['channel'] = (0 === strpos($channel, '#') ? $channel : (0 === strpos($channel, '@') ? $channel : '#' . $channel));
    }
    return $this;
}
```

to

```php
public function setChannel($channel)
{
    if (!empty($channel)) {
        $this->data['channel'] = (0 === strpos($channel, ':') ? ltrim($channel, ':') : (0 === strpos($channel, '#') ? $channel : (0 === strpos($channel, '@') ? $channel : '#' . $channel)));
    }
    return $this;
}
```

Please let me know what you think of this solution. If you think it's adequate I'll submit the pull request otherwise we can discuss an alternative.

Thanks!

**Comment by mcrumm** [comment]
Thanks for reporting this!

Since there is more than one valid use case for channels that should not be automatically prefixed, my preference would be to stop trying to "normalize" channel strings entirely.

I seriously considered dropping the channel normalizer when the last PR came in to support @ mentions, because nested ternary operations make me queasy. :grimacing:

If you'd like to submit a PR that *removes* the channel normalizer and the ternary in `setChannel`, I would definitely accept it.  I'll need to tag a `0.6.x` release, since this would technically be a BC break.

**Comment by errodr** [comment]
Sounds good. I'll do that, much better option. Not a big fan of ternary operations myself.

Thanks!
