### ISSUE TITLE
"text" is not obligatory in messages

### ISSUE THREAD

**Issue by rdohms** [mcrumm/phlack#30]
Was using the message builder and it says i need to add text before calling `create`, but while using the Slack API i noticed that you can set `text` in the attachment, so this is not necessary.

Any thoughts on this?

**Comment by mcrumm** [comment]
IIRC, `text` is required for simple messages, but if it's optional when a message contains attachments, then I would definitely like to support that use case.

The process for resolving the `text` property on `Message` will likely need to be tweaked to check for the existence of any attachments, and only require `text` when no attachments exist.  This is easiest to do in `MessageBuilder`, since it knows about the attachments prior to creating the message.  `Message`, on the other hand, resolves its options in its constructor, which is problematic, especially given that there's no current mechanism to pass attachments to a `Message` during construction.

It's entirely possible I'm trying too hard to save developers from themselves by being so strict with the message options.  The simplest solution might be to drop `text` as a required field, and document the fact that it **is** required for simple messages, but if you forget to add it, Phlack won't raise an exception prior to sending the message to Slack.

I'm open to a PR to support this.  I'd love to hear your thoughts on whether or not there's any advantage to the strict property checks that are currently in place.

**Comment by rdohms** [comment]
@mcrumm i also noticed that fallback is required when its actually not. So i have been using JS slack integrations for a while and am now writing a PHP version of those plugins. I honestly think the over-protection is more getting in my way then just getting plain errors from slack.

So if you ask me, we can just drop all the "slack" rules and only check properties and such that are request problems in general. With JS its mostly about sending a json payload so there is very little to no validation being done, slack does a good job of reporting what you did wrong. Also most of these errors are development errors, not runtime issues in most cases, its not like i can catch a exception and cook up a text or fallback, we would do that in building anyway.

Anyway, my 2 cents.
